[build]
  command = "hugo --gc --minify"
  context = "production"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"

[context.production.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "production"